# Change these first
owner: Quozul # Your GitHub username
repo: quozul.github.io # Your GitHub repository name

# Add your sites here
sites:
  - name: Quozul.dev
    url: https://quozul.dev/

status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  cname: status.quozul.dev
  # Uncomment the following line if you don't have a custom domain and add your repo name
  # baseUrl: /upptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Quozul.dev Status
  introTitle: "**Quozul.dev** uptime monitor and status page, powered by Upptime."
  introMessage: 
  navbar:
    - title: Status
      href: /
    - title: Quozul.dev
      href: https://quozul.dev/
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
